### ISSUE TITLE
ReactiveImagePicker / ReactiveFilePicker

### ISSUE THREAD

**Issue by Reprevise** [artflutter/reactive_forms_widgets#1]
I'd love to see a ReactiveImagePicker and/or a ReactiveFilePicker.

**Comment by vasilich6107** [comment]
In progress

**Comment by vasilich6107** [comment]
released in v0.3.8

**Comment by Reprevise** [comment]
What about a `ReactiveFilePicker` widget using the `file_picker` package?

**Comment by vasilich6107** [comment]
@Reprevise may be some day.
Do you have any implementation examples of nice UI?
Currently I do not imagine what to display after random file was picked...

**Comment by Reprevise** [comment]
@vasilich6107 If it's anything other than an image, I'd suggest just showing the file name. Though if it's something like a PDF, maybe a little preview of the first page.

**Comment by mrverdant13** [comment]
I think it would be acceptable to provide a `previewBuilder` so we could decide what to display.
Maybe, if this builder is not provided, a simple icon placeholder could be used as default (depending on the selected file extension, of course).

**Comment by vasilich6107** [comment]
@Reprevise @mrverdant13 check https://pub.dev/packages/reactive_file_picker
