### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by maanhaider** [artflutter/reactive_forms_widgets#11]
It is not compatible with reactive form version 9.1.0. Any update regarding that ?

**Comment by vasilich6107** [comment]
We are currently moving to monorepo

Check individual packages
https://github.com/artflutter/reactive_forms_widgets/issues/6#issuecomment-791905298

**Comment by vasilich6107** [comment]
@maanhaider any feedback?

**Comment by maanhaider** [comment]
I didn't check it yet because of my busy schedule . Will try it soon and then give you feedback :)

**Comment by vasilich6107** [comment]
Closing this issue for now. Feel free to open new one if there will be any issues
