### ISSUE TITLE
font size in ReactiveDropdownSearch

### ISSUE THREAD

**Issue by rodriger06** [artflutter/reactive_forms_widgets#13]
Hi, I would like to know how to change the font size in ReactiveDropdownSearch for the selected items and for the list of items in the popup. I tried using style like
```
  style: TextStyle(
          fontSize: 20,
      ),
```
but ReactiveDropdownSearch doesnt recognize it.

here is my code
```
Widget frequencyField(BuildContext context) {
    return  ReactiveDropdownSearch<String>(
      formControlName: frequencyLabel,
      mode: ReactiveDropdownSearchMode.DIALOG,
      items: ["Weekly", "Bi-Weekly", "Monthly", 'Quarterly', 'Yearly', 'One Time'],
     
      decoration: InputDecoration(
        border: new OutlineInputBorder(
            borderSide: new BorderSide(color: Colors.teal)),
        // labelText: incomeAmount,
        prefixIcon: Icon(Icons.refresh),
        contentPadding: EdgeInsets.fromLTRB(0,6.5,0,6.5),
        labelStyle: TextStyle(fontSize: text_size_18),
      ),
      label: frequencyLabel,
      showSearchBox: true,
      popupTitle: Container(
        height: margin_50dp,
        decoration: BoxDecoration(
          color: Theme.of(context).primaryColorDark,
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(10),
            topRight: Radius.circular(10),
          ),
        ),
        child: Center(
          child: Text(
            frequencyLabel,
            style: TextStyle(
              fontSize: 24,
              fontWeight: FontWeight.bold,
              color: Colors.white,
            ),
          ),
        ),
      ),
      popupShape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(margin_10dp),
      ),
    );
  }
```
take a look at the pics attached at the text circled in red. I want to increase the font size of the selected item as well as the items in the popup screen

<img width="184" alt="freq_font_increase" src="https://user-images.githubusercontent.com/49496303/119210249-3c469580-ba79-11eb-913d-1fe93337c33b.PNG">
<img width="183" alt="freq_font_increase2" src="https://user-images.githubusercontent.com/49496303/119210250-3c469580-ba79-11eb-8a2b-397ab908997f.PNG">

thanks in advance

**Comment by vasilich6107** [comment]
Hi. You can find `example` of how to highlight the selected item here

https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/example/lib/main.dart#L391

**Comment by vasilich6107** [comment]
In case of future issues first - take a look at readme file in this repo
https://github.com/artflutter/reactive_forms_widgets

There is a list of links to corresponding widgets that we are using to create `Reactive...` counterparts.

It will be better to re-route your questions to the original package maintainer cause we just pass through properties and could not know all possible options.
