### ISSUE TITLE
Discontinued on pub.dev ?

### ISSUE THREAD

**Issue by FuretBicephale** [artflutter/reactive_forms_widgets#14]
Hi,

On [pub.dev](https://pub.dev/packages/reactive_forms_widgets), this package is tagged as discontinued but seems to be active here. Is this an error on pub.dev or is this package aborted ?

**Comment by vasilich6107** [comment]
@FuretBicephale this package was a bundle from the initial release.
Then we transitioned to monorepo and separated releases
Every control has it's own package now

https://pub.dev/packages/reactive_advanced_switch
https://pub.dev/packages/reactive_date_range_picker
https://pub.dev/packages/reactive_date_time_picker
https://pub.dev/packages/reactive_dropdown_search

and so on
