### ISSUE TITLE
ReactiveDropdownSearchMultiSelection Hint Text alignment

### ISSUE THREAD

**Issue by lohenyumnam** [artflutter/reactive_forms_widgets#21]
### Info

Flutter 2.5.2
reactive_forms: ^10.6.2
reactive_dropdown_search: ^0.5.0

### Problem:

`ReactiveDropdownSearchMultiSelection` hint Text does not vertically center align with `dropDownButton` the code I use is given down below.

```dart
ReactiveDropdownSearchMultiSelection<String, String>(
              formControlName: SetupFromFieldsName.cuisine,
              dropdownSearchTextAlignVertical: TextAlignVertical.top,
              decoration: InputDecoration(
                filled: true,
                fillColor: KColors.shade300,
                hintText: 'HintText ' * 10,
                hintStyle: context.textTheme.subtitle1?.copyWith(
                  textBaseline: TextBaseline.alphabetic,
                  color: KColors.textLight,
                  height: 1.9,
                ),
                contentPadding: const EdgeInsets.symmetric(vertical: 8),
                border: const OutlineInputBorder(),
              ),
              mode: Mode.BOTTOM_SHEET,
              showSelectedItems: true,
              items: const [
                "Brazil",
                "Italia",
                "Tunisia",
                'Canada',
                'France',
              ],
              showSearchBox: true,
            )
```

![image](https://user-images.githubusercontent.com/17508663/140473154-05485efc-431b-4c95-b0f0-7a7ed93a2b4d.png)

but If I select the Item it works fine

![image](https://user-images.githubusercontent.com/17508663/140473444-8f4fc80a-2e4c-4c77-b27b-a01a14cb9e35.png)

**Comment by vasilich6107** [comment]
@lohenyumnam refer to the original package dosc to find and answer 
https://github.com/salim-lachdhaf/searchable_dropdown

`ReactiveDropdownSearchMultiSelection` just passes through the props

**Comment by vasilich6107** [comment]
@lohenyumnam you can also try to set this param to true 

https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/dropdown_search.dart#L190

**Comment by lohenyumnam** [comment]
> @lohenyumnam you can also try to set this param to true
> 
> https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/dropdown_search.dart#L190

This solves the problem, but as suggested I when through there example code and found out the I can customize even more so now I have created a custom widget and build using `dropdownBuilder`
