### ISSUE TITLE
ImagePickerWidget doesn't take "enable" property

### ISSUE THREAD

**Issue by AlexSmirnov9107** [artflutter/reactive_forms_widgets#22]
ImagePickerWidget doesn't take "enable" property from ReactiveImagePicker

<img width="752" alt="image" src="https://user-images.githubusercontent.com/32673518/141672096-18daea59-5e84-4e71-a0cc-1d8fd1909439.png">

**Comment by vasilich6107** [comment]
Hi @AlexSmirnov9107 
Will take a look in 10 days after vacation

**Comment by vasilich6107** [comment]
@AlexSmirnov9107 check v0.5.0
https://pub.dev/packages/reactive_image_picker
