### ISSUE TITLE
ReactiveSegmentedControl - displays a 'line' underneath the component

### ISSUE THREAD

**Issue by SogoGolf** [artflutter/reactive_forms_widgets#24]
hi, why is this line displaying underneath when the ReactiveSegmentedControl renders ? I could not find a way to get rid of it. Appreciate if you can let me know, thanks

![IMG_0BEF9D0093ED-1](https://user-images.githubusercontent.com/19580787/144946216-31cd1e1f-332d-4062-b8e7-31ce176d643a.jpeg)

**Comment by vasilich6107** [comment]
@SogoGolf this is input decoration 
https://github.com/artflutter/reactive_forms_widgets/blob/master/packages/reactive_segmented_control/lib/reactive_segmented_control.dart#L91

Adjust for your needs according to the docs
https://api.flutter.dev/flutter/material/InputDecoration-class.html

**Comment by SogoGolf** [comment]
ah yes ur right thanks, i found that and made adjustment fine

**Comment by vasilich6107** [comment]
@SogoGolf 
I created a package https://pub.dev/packages/reactive_forms_generator which helps to cover tricky parts of the reactive_forms with power of generators.
The motivation section from readme describes my intentions
https://github.com/artflutter/reactive_forms_generator#motivation

It would be great if you could try it and provide some feedback)
