### ISSUE TITLE
ReactiveImagePicker Pass value to Firebase

### ISSUE THREAD

**Issue by alshueiliproject** [artflutter/reactive_forms_widgets#25]
hi
I'm using **ReactiveImagePicker** with ReactiveFormBuilder
I have difficult to passing value from **ReactiveImagePicker**  ReactiveFormBuilder  to the Firebase
 
```
 
   FormGroup form() => fb.group({
        'ownerName': FormControl<String>(
            value: ownerName, validators: [Validators.required]),
        'ownerImage':
            FormControl<ImageFile>(validators: [Validators.required]),
      });

   var _image = data["ownerImage"]; //// data from ReactiveFormBuilder
  File file =File(_image);   ///  pass value to File (_error )

    await ref.putFile(file);   Upload file 
   var  imageurl = await ref.getDownloadURL(); // get url Image 

 
 
```

[reactive_image_picker](https://pub.dev/packages/reactive_image_picker/example)
[reactive_forms 10.6.7](https://pub.dev/packages/reactive_forms)
[stackoverflow](https://stackoverflow.com/questions/51338041/how-to-save-image-file-in-flutter-file-selected-using-image-picker-plugin)

**Comment by vasilich6107** [comment]
Hi @alshueiliproject check the structure of the output of plugin 
https://github.com/artflutter/reactive_forms_widgets/blob/master/packages/reactive_image_picker/lib/image_file.dart

and select the property that suits best for your needs

**Comment by alshueiliproject** [comment]
Thank you for replay .


[https://github.com/artflutter/reactive_forms_widgets/blob/master/packages/reactive_image_picker/example/lib/main.dart](https://github.com/artflutter/reactive_forms_widgets/blob/master/packages/reactive_image_picker/example/lib/main.dart)

I'm working as same above example  and my problem is to get the path of the image and pass it to the firebase ,,,, 
 

```
   ElevatedButton(
                            child: Text('Sign Up'),
                            onPressed: () {
                              if (form.valid) {

                                 ImageFile _image = form.value["ownerImage"];  //// error to pass ImageSource 
                                print(form.value);

                              } else {
                                form.markAllAsTouched();
                              }
                            },
                          ),
```

**Comment by vasilich6107** [comment]
There is an image prop in object with file

**Comment by vasilich6107** [comment]
Launch example project in debug 
Put a breakpoint onto print and check what's inside the form value 
There should be image or path initialized
I do not remember exactly

**Comment by alshueiliproject** [comment]
Problem solved, file uploaded successfully, Thank a lot.

**Comment by vasilich6107** [comment]
@alshueiliproject 
I created a package https://pub.dev/packages/reactive_forms_generator which helps to cover tricky parts of the reactive_forms with power of generators.
The motivation section from readme describes my intentions
https://github.com/artflutter/reactive_forms_generator#motivation

It would be great if you could try it and provide some feedback)
