### ISSUE TITLE
Expose initialValue for ReactiveRawAutocomplete

### ISSUE THREAD

**Issue by JesperBllnbm** [artflutter/reactive_forms_widgets#26]
Hi there,

great work thanks a lot!
I have a minor thing which could be fixed super quickly. It would be cool if you could expose the initialValue for the ReactiveRawAutocomplete Widget. 
The background is that I might want to feed the autocomplete suggestions with a data model which is more complex than just a string. With the `displayStringForOption` function I can control how my data model is represented as a string. It would be great if I could have the same control for the initialValue. Right now the data model is simply parsed to string:

```
  @override
  void initState() {
    super.initState();

    final initialValue = value;
    _textController = TextEditingController(
        text: initialValue == null ? '' : initialValue.toString());
  }
```

it would be great to have something like that:

```
  @override
  void initState() {
    super.initState();

    final initialValue = widget.initialValue ?? value;
    _textController = TextEditingController(
        text: initialValue == null ? '' : initialValue.toString());
  }
```

**Comment by vasilich6107** [comment]
Hi @JesperBllnbm 

You need to use `FormControl`

```dart
final form = FormGroup({
  'input': FormControl<WhateverTypeYouWant>(value: ...),
});
```

to specify initial value for your field

**Comment by JesperBllnbm** [comment]
Thanks for your quick reply!
That is understood - where I struggle is when I have something like that:

```
class Fruit {
String name;
Color color;
}
```

```
  ReactiveRawAutocomplete<String, Fruit>(
...
)
```

When using a `ValueAccessor` I always end up to have an initialValue like `Fruit(name:banana, color:yellow)` what I would like to have is just `banana`. Which is possible later by using the `displayStringForOption` function. 

I hope that explains it a bit better :)

**Comment by vasilich6107** [comment]
May me you have issues with `ValueAccessor`?

**Comment by vasilich6107** [comment]
The rawautocomplete state that initial value is ignored when we use controller
This package uses controller so the initialValue param will be ignored)

**Comment by vasilich6107** [comment]
You can create the reproduction repo with your issue - i will try to find time to help you

**Comment by JesperBllnbm** [comment]
> The rawautocomplete state that initial value is ignored when we use controller
> This package uses controller so the initialValue param will be ignored)

this makes sense! thanks for clarifying :)

**Comment by vasilich6107** [comment]
@JesperBllnbm 
I created a package https://pub.dev/packages/reactive_forms_generator which helps to cover tricky parts of the reactive_forms with power of generators.
The motivation section from readme describes my intentions
https://github.com/artflutter/reactive_forms_generator#motivation

It would be great if you could try it and provide some feedback)
