### ISSUE TITLE
Please update freezed_annotation dependency version

### ISSUE THREAD

**Issue by ferrerogg** [artflutter/reactive_forms_widgets#27]
Current  reactive_file_picker (both 0.3.0 and 0.4.0) depends on freezed_annotation ^0.14.3.
My project is using freezed_annotation ^1.1.0, so version check is failing

```
[next_crm_app] flutter pub get
Running "flutter pub get" in next_crm_app...                    
Because reactive_file_picker 0.4.0 depends on freezed_annotation ^0.14.3 and no versions of reactive_file_picker match >0.4.0 <0.5.0, reactive_file_picker ^0.4.0 requires freezed_annotation ^0.14.3.
So, because next_crm_app depends on both freezed_annotation ^1.1.0 and reactive_file_picker ^0.4.0, version solving failed.
pub get failed (1; So, because next_crm_app depends on both freezed_annotation ^1.1.0 and reactive_file_picker ^0.4.0, version solving failed.)
exit code 1
```

At the moment I've fixed this by enforcing freezed_annotation ^1.1.0 in dependency_overrides

**Comment by vasilich6107** [comment]
Check latest version

**Comment by vasilich6107** [comment]
@ferrerogg 
I created a package https://pub.dev/packages/reactive_forms_generator which helps to cover tricky parts of the reactive_forms with power of generators.
The motivation section from readme describes my intentions
https://github.com/artflutter/reactive_forms_generator#motivation

It would be great if you could try it and provide some feedback)
