### ISSUE TITLE
 Autocomplete add a stringToViewModel function

### ISSUE THREAD

**Issue by JesperBllnbm** [artflutter/reactive_forms_widgets#28]
Hi there,

I had another idea how to improve the ReactiveRawAutocomplete Widget. Right now only values that already exist can be selected and `field.didChange` is only called `onSelected`. It would be great if we could use the same input field also for creating a new instance of `T` when they not yet exist. I prepared an example:

[here](https://github.com/JesperBllnbm/reactive_forms_widgets/commits/master)

In the example you can select existing fruits from the autocomplete but also create new ones using the same input field.

**Comment by vasilich6107** [comment]
@JesperBllnbm 
what's the point of having `stringToViewModel`?
It is bound to `onChanged` in your implementation
Could you describe in details what are you trying to improve?

**Comment by vasilich6107** [comment]
@JesperBllnbm 
Could you describe in details what are you trying to improve?

**Comment by vasilich6107** [comment]
Closing issue due to the lack of response.
feel free to reopen
