### ISSUE TITLE
Upgrade to depend on reactive_forms 11

### ISSUE THREAD

**Issue by BenjaminFarquhar** [artflutter/reactive_forms_widgets#29]
Hi, just wondering if it is in the roadmap to upgrade to use `reactive_forms` 11. I use the `reactive_touch_spin` to be more specific.

Thanks

**Comment by vasilich6107** [comment]
@BenjaminFarquhar 
I created a package https://pub.dev/packages/reactive_forms_generator which helps to cover tricky parts of the reactive_forms with power of generators.
The motivation section from readme describes my intentions
https://github.com/artflutter/reactive_forms_generator#motivation

It would be great if you could try it and provide some feedback)

**Comment by BenjaminFarquhar** [comment]
@vasilich6107  I am finally having a good go at this. My favourite thing is that the `formModel.model` keeps the strongly typed entity in sync with the form by default and is always accessible. I like to use model binding in my forms. This is awesome. I'm probably going to completely migrate my app to use it. Is updating it to work with reactive_forms 11 in the pipeline?

**Comment by vasilich6107** [comment]
I will update to rf11 tomorrow

**Comment by vasilich6107** [comment]
@BenjaminFarquhar migrated to v11
