### ISSUE TITLE
ReactiveDateTimePicker is missing touched handling

### ISSUE THREAD

**Issue by kuhnroyal** [artflutter/reactive_forms_widgets#3]
The widget should probably set the `touched` field of the control when a tap occurs.

**Comment by vasilich6107** [comment]
Hi. I'll check

**Comment by vasilich6107** [comment]
@kuhnroyal should be fixed in v0.3.7

**Comment by kuhnroyal** [comment]
Yes the error messages work now when the field is touched.

**Comment by vasilich6107** [comment]
v0.4.0 has slightly updated touched handling
check the changelog https://github.com/artflutter/reactive_forms_widgets/blob/master/CHANGELOG.md

**Comment by kuhnroyal** [comment]
@vasilich6107 In the new `reactive_date_time_picker` the control needs to be marked as touched when the clear button is pressed.

**Comment by vasilich6107** [comment]
@kuhnroyal check v0.0.3

**Comment by kuhnroyal** [comment]
Thanks, that was quick :)
