### ISSUE TITLE
General use

### ISSUE THREAD

**Issue by Gazzolla** [artflutter/reactive_forms_widgets#30]
How to use with items type DropdownMenuItem in ReactiveDropdownSearch?

**Comment by vasilich6107** [comment]
Check
https://github.com/artflutter/reactive_forms_widgets/tree/master/packages/reactive_dropdown_field

**Comment by Gazzolla** [comment]
Ok, but what I need is the searchable one at 

https://github.com/artflutter/reactive_forms_widgets/blob/master/packages/reactive_dropdown_search/example/lib/main.dart

 I don't understand how I can do to display a value and have another hidden

**Comment by vasilich6107** [comment]
You do not have an ability to use DropdownMenuItem in ReactiveDropdownSearch.

**Comment by vasilich6107** [comment]
See the original package for more examples
https://github.com/salim-lachdhaf/searchable_dropdown

**Comment by vasilich6107** [comment]
You can also check the bundled example of usage
https://github.com/artflutter/reactive_forms_widgets/tree/master/packages/reactive_dropdown_search/example
