### ISSUE TITLE
Unable to add reactive_forms_widget to my project

### ISSUE THREAD

**Issue by snandiga** [artflutter/reactive_forms_widgets#31]
I created a new flutter project and did the following:

 **flutter pub add reactive_forms** This command ran fine.

After that i ran the following and I am getting an error.

**flutter pub add reactive_forms_widgets**

Because reactive_forms >=9.1.0 depends on intl ^0.17.0 and flutter_touch_spin >=1.0.1 <2.0.0-nullsafety.0 depends on intl ^0.16.1, reactive_forms >=9.1.0 is incompatible with flutter_touch_spin >=1.0.1 <2.0.0-nullsafety.0.
And because every version of reactive_forms_widgets depends on flutter_touch_spin ^1.0.1, reactive_forms >=9.1.0 is incompatible with reactive_forms_widgets.
So, because ftest depends on both reactive_forms ^11.0.0 and reactive_forms_widgets any, version solving failed.
pub finished with exit code 65

**Comment by vasilich6107** [comment]
Update all packages to latest versions

**Comment by snandiga** [comment]
I have done that.
flutter channel stable
flutter upgrade
Then created the project and installed reactive_forms and reactive_forms_widgets 
That is when I was getting this error

**Comment by vasilich6107** [comment]
It would be more productive if you provide your pubspec yaml file

**Comment by vasilich6107** [comment]
You do not have to install reactive_forms_widgets

You have to install each widget separately

**Comment by vasilich6107** [comment]
the original package is discontinued
https://pub.dev/packages/reactive_forms_widgets

**Comment by snandiga** [comment]
Thanks for helping me out. I installed the widgets i needed and it worked.

**Comment by vasilich6107** [comment]
@snandiga 

I created a package https://pub.dev/packages/reactive_forms_generator which helps to cover tricky parts of the reactive_forms with power of generators.
The motivation section from readme describes my intentions
https://github.com/artflutter/reactive_forms_generator#motivation

It would be great if you could try it and provide some feedback)

Do not forget to star this repo if it helps you in your day to day tasks ;-)
