### ISSUE TITLE
type 'Null' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by qq2276031** [artflutter/reactive_forms_widgets#32]
type 'Null' is not a subtype of type 'String' in type cast
Error in reactive_awesome_select
ReactiveSmartSelectSingle

**Comment by vasilich6107** [comment]
Make the type String?

**Comment by vasilich6107** [comment]
@qq2276031 any feedback?

**Comment by vasilich6107** [comment]
Closing due to the missing response
Feel free to reopen

**Comment by leandrorazevedo** [comment]
same problem
