### ISSUE TITLE
how to disabled ReactiveDropdownSearch and ReactiveDateTimePicker 

### ISSUE THREAD

**Issue by rodriger06** [artflutter/reactive_forms_widgets#33]
Hi I love using reactive forms widgets specially ReactiveDropdownSearch and ReactiveDateTimePicker .
I have an app where in some cases i need to disable   ReactiveDropdownSearch and ReactiveDateTimePicker in my form so that the user cannot click and pick a value.  however, I am not able to find out how to do it.  is there an attribute like  disable: true that i can use in these two widgets so that they become disabled (gray out)  and nothing happens when user click on them?

thanks
ER

**Comment by vasilich6107** [comment]
Hi
Check the `FormControl`
It has bool attr for this purposes

**Comment by vasilich6107** [comment]
https://github.com/joanpablo/reactive_forms#how-enabledisable-a-widget

**Comment by vasilich6107** [comment]
@rodriger06 any feedback?

**Comment by vasilich6107** [comment]
Closing due to the missing response
Feel free to reopen
