### ISSUE TITLE
How to handle on ReactiveDateTimePicker Change 

### ISSUE THREAD

**Issue by alshueiliproject** [artflutter/reactive_forms_widgets#34]
I want to count the days between going and coming back
My question is how to get the value when selecting the date ?

My code 
`   ReactiveDateTimePicker(
                          firstDate: DateTime.now(),
                          formControlName: 'returnDate',
                          type: ReactiveDatePickerFieldType.dateTime,
                          decoration: const InputDecoration(
                            labelText: 'Return Date',
                            border: OutlineInputBorder(),
                            helperText: '',
                            suffixIcon: Icon(Icons.calendar_today),
                          ),
                          validationMessages: (control) {
                            return {'required': 'required'};
                          },
                          //  valueAccessor: _onChange(va)
                          
                          
                          ),`

https://pub.dev/packages/reactive_date_time_picker/example

**Comment by vasilich6107** [comment]
hi @alshueiliproject 

Check
https://github.com/joanpablo/reactive_forms/blob/master/lib/src/widgets/reactive_value_listenable_builder.dart

**Comment by vasilich6107** [comment]
hi @alshueiliproject any feedback?

**Comment by vasilich6107** [comment]
Closing the issue.
No feedback from author.
Feel free to reopen
