### ISSUE TITLE
ReactiveMultiImagePicker open and close when i try to pick images 

### ISSUE THREAD

**Issue by abanoubEssam** [artflutter/reactive_forms_widgets#35]
ReactiveMultiImagePicker(
      enableCamera: true,
      maxImages: 20,
      formControlName: pickerControlName,
      imagePickerBuilder: (pickImage, images, onChange) {
        return GestureDetector(
          onTap: pickImage,
          child: Container(
            child: Text("Upload Images"),
          ),
        );
      },
    );

**Comment by vasilich6107** [comment]
Could you be more verbose in issue description?
Did you try to lunch project from example folder?

**Comment by vasilich6107** [comment]
Multi image picker discontinued 
So I do not recommend to use it
https://pub.dev/packages/multi_image_picker

**Comment by abanoubEssam** [comment]
i just added this line to AndroidManifest.xml 
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
and it works now 
@vasilich6107
