### ISSUE TITLE
reactive_multi_image_picker  how to get file path ?

### ISSUE THREAD

**Issue by abanoubEssam** [artflutter/reactive_forms_widgets#36]

**Comment by vasilich6107** [comment]
@abanoubEssam 
Please do not create duplicated issue everywhere you can.

**Comment by abanoubEssam** [comment]
i closed the other one @vasilich6107

**Comment by vasilich6107** [comment]
@abanoubEssam `multi_image_picker` does not have `path` it operates only with asset identifier. You can get content of the file with `asset.getByteData()`

**Comment by vasilich6107** [comment]
@abanoubEssam any feedback?

**Comment by vasilich6107** [comment]
No response
Closing the issue
Feel free to reopen
