### ISSUE TITLE
reactive_touch_spin doesn't display programmatic value updates

### ISSUE THREAD

**Issue by BenjaminFarquhar** [artflutter/reactive_forms_widgets#37]
reactive_touch_spin only displays updated values from clicking the up and down arrows to change the number, not from resetting the form values or calling updateValue() or any of the other numerous ways of changing the value programmatically using reactive_forms.

**Comment by BenjaminFarquhar** [comment]
To recreate - edit the example app - example/lib/main.dart and make the sign up button update the value:

```
ElevatedButton(
  child: const Text('Sign Up'),
  onPressed: () {
    if (form.valid) {
      // ignore: avoid_print
      form.control('touchSpin').updateValue(50);
      print(form.value);
    } else {
      form.markAllAsTouched();
    }
  },
),
```

**Comment by BenjaminFarquhar** [comment]
I don't think you'll be able to use flutter_touch_spin [due to this issue](https://github.com/danvick/flutter_touch_spin/issues/13). A fairly massive flaw in the widget if you ask me. 

It kind of makes the widget, not a reactive_forms widget as it is unresponsive to reactive_forms.

**Comment by vasilich6107** [comment]
Hi @BenjaminFarquhar 
Thanks for investigating.

It seems that I will need to make PR one more time and release a temp substitution for the control)
After making PR i will ask you to tag the maintainer for releasing an update.

**Comment by BenjaminFarquhar** [comment]
@vasilich6107 You're welcome! Sure, will do.

**Comment by vasilich6107** [comment]
https://github.com/danvick/flutter_touch_spin/pull/14

**Comment by vasilich6107** [comment]
@BenjaminFarquhar check latest version

**Comment by BenjaminFarquhar** [comment]
@vasilich6107 I will do thank you. I have confirmed it is working. Thanks for the quick fix.

**Comment by BenjaminFarquhar** [comment]
@vasilich6107  in version 0.4.0 I get the error:

setState() or markNeedsBuild() called during build.

When I go back to ^0.3.0-nullsafety.2 I don't get the error. I don't have time right now to investigate so I'm staying on ^0.3.0-nullsafety.2 as everything is working fine for me on that - changing the value from the outside is also working in that version.

**Comment by vasilich6107** [comment]
Could you provide reproduction code?

**Comment by BenjaminFarquhar** [comment]
@vasilich6107  The bug occurs when you run the example project and click on the arrows in the widget with the mouse

**Comment by vasilich6107** [comment]
@BenjaminFarquhar 
here is my PR updates
<img width="577" alt="image" src="https://user-images.githubusercontent.com/6721286/152822508-55980398-4f42-4fde-9054-eb91aca0fc6f.png">


here is what inside
<img width="506" alt="image" src="https://user-images.githubusercontent.com/6721286/152822740-ac56a697-721f-4898-b787-074ca1039ff3.png">

**Comment by vasilich6107** [comment]
I do not know why author added setState call

**Comment by vasilich6107** [comment]
@BenjaminFarquhar 

From flutter docs
```
The framework always calls [build](https://api.flutter.dev/flutter/widgets/State/build.html) after calling [didUpdateWidget](https://api.flutter.dev/flutter/widgets/State/didUpdateWidget.html), which means any calls to [setState](https://api.flutter.dev/flutter/widgets/State/setState.html) in [didUpdateWidget](https://api.flutter.dev/flutter/widgets/State/didUpdateWidget.html) are redundant.```

**Comment by vasilich6107** [comment]
@BenjaminFarquhar check latest version
reactive_touch_spin: ^0.4.1

**Comment by BenjaminFarquhar** [comment]
Cool, thanks @vasilich6107
