### ISSUE TITLE
Allow nullable dates for ReactiveDateTimePicker

### ISSUE THREAD

**Issue by Tienisto** [artflutter/reactive_forms_widgets#39]
My form has a date field, which is optional but the type of `ReactiveDateTimePicker` is hard coded to `DateTime`.

My form:
```dart
final form = FormGroup({
      'firstMonth': FormControl<DateTime>(
        value: agreement?.firstMonth,
        validators: [Validators.required],
      ),
      'lastMonth': FormControl<DateTime?>(
        value: agreement?.lastMonth,
        validators: [],
      ),
    });
```

What should I do in this case?

**Comment by lukey78** [comment]
With the null safety in newer Flutter versions this example of the nullableDate does not work anymore.
