### ISSUE TITLE
Reactive fancy password field obscure text not working

### ISSUE THREAD

**Issue by CharlyZA-2** [artflutter/reactive_forms_widgets#40]
The obscureText parameter is not being passed to the wrapped child component "FancyPasswordField".

Additionally, I'm not sure if the issue lies in my code or the wrapped library but I'm unable to get the hide/show button to show as is shown on the first demo on their page. I've tried changing all the parameters relating to hiding/showing. This is not an issue if I can implement it myself using the obscureText parameter with an icon button.

**Comment by vasilich6107** [comment]
@CharlyZA-2 fixed in reactive_fancy_password_field 0.0.3

**Comment by CharlyZA-2** [comment]
Thank you :)
