### ISSUE TITLE
No named parameter with the name 'selectorNavigator'

### ISSUE THREAD

**Issue by natino45** [artflutter/reactive_forms_widgets#46]
Looks like new update for PhoneFormField does not have selectorNavigator parameter and it's causing an error.

https://github.com/artflutter/reactive_forms_widgets/blob/22258dd274172cd9c4a490ebf44fbd405b7f6d0a/packages/reactive_phone_form_field/lib/reactive_phone_form_field.dart#L177

**Comment by vasilich6107** [comment]
check reactive_phone_form_field 0.3.0
