### ISSUE TITLE
ReactiveRawAutocomplete doesn't work if I delete the text in the field to clear it

### ISSUE THREAD

**Issue by sgehrman** [artflutter/reactive_forms_widgets#47]
I have a state popup.  I select a state and that works, but if I delete the state, it doesn't update the form data.

**Comment by vasilich6107** [comment]
@sgehrman could you provide copypasta or reproduction code?

**Comment by vasilich6107** [comment]
@sgehrman any feedback?

**Comment by vasilich6107** [comment]
Closing due to missing feedback
