### ISSUE TITLE
Reactive datetime picker does not work with   reactive_forms v^12.0.0

### ISSUE THREAD

**Issue by red23495** [artflutter/reactive_forms_widgets#49]
I get the following error when I install dependencies for my project
`
Because reactive_date_time_picker >=0.2.0 depends on reactive_forms ^11.0.0 and builder_app depends on reactive_forms ^12.0.0, reactive_date_time_picker >=0.2.0 is forbidden.
So, because builder_app depends on reactive_date_time_picker ^0.2.2, version solving failed.
`

Please update the dependency of the package so that it can be used with the latest reactive form.

**Comment by vasilich6107** [comment]
Use dependancy overrides until update

**Comment by vasilich6107** [comment]
use latest reactive_date_time_picker: ^0.3.0
