### ISSUE TITLE
ReactiveDropdownSearch : how to know when on change item

### ISSUE THREAD

**Issue by softwarebam** [artflutter/reactive_forms_widgets#5]
how to know when on change item of ReactiveDropdownSearch

**Comment by vasilich6107** [comment]
You have two options

- https://pub.dev/packages/reactive_forms#reactivevaluelistenablebuilder-to-listen-when-value-changes-in-a-formcontrol
- use `onBeforeChange` callback of `ReactiveDropdownSearch` https://github.com/salim-lachdhaf/searchable_dropdown/blob/master/lib/dropdown_search.dart#L164

**Comment by vasilich6107** [comment]
@softwarebam did it help you?
