### ISSUE TITLE
reactive_phone_form_field country code position moved to right

### ISSUE THREAD

**Issue by natino45** [artflutter/reactive_forms_widgets#50]
Hi, 

After updating reactive_phone_form_field  position of the country code has moved to the right but trigger to open country selector remains on the left. 

I was able to change position by setting  `textDirection: TextDirection.ltr` 

Is it a bug or we need to set text directions now ?

**Comment by vasilich6107** [comment]
@natino45 I do not know
I just pass params through

You'd better create this type of issues in original package repo
https://github.com/cedvdb/phone_form_field/

Maybe @cedvdb could answer this time

**Comment by vasilich6107** [comment]
also do not forget to check the example https://github.com/cedvdb/phone_form_field/tree/dev/example

**Comment by cedvdb** [comment]
It's a bug from the version 5.0.2. It should be a relatively easy fix but I'm currently very busy.

There is already an issue created for it in the repository.

**Comment by cedvdb** [comment]
fixed in latest version

**Comment by cedvdb** [comment]
Hello again. The package version with the fix that should be used is 6.0.0. The other version posted above has been retracted because the compatibility with flutter 3 introduces a breaking change.

**Comment by vasilich6107** [comment]
@cedvdb will update the package today
Thanks

**Comment by vasilich6107** [comment]
reactive_phone_form_field: ^0.5.0
