### ISSUE TITLE
Support flutter 3.0

### ISSUE THREAD

**Issue by hs029** [artflutter/reactive_forms_widgets#51]
See this error:

../../../appdev/flutter/.pub-cache/hosted/pub.flutter-io.cn/dropdown_search-3.0.1/lib/dropdown_search.dart:519:26: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../appdev/flutter/packages/flutter/lib/src/widgets/binding.dart').
          WidgetsBinding.instance?.addPostFrameCallback((_) {
                         ^
../../../appdev/flutter/.pub-cache/hosted/pub.flutter-io.cn/dropdown_search-3.0.1/lib/dropdown_search.dart:551:26: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../appdev/flutter/packages/flutter/lib/src/widgets/binding.dart').
          WidgetsBinding.instance?.addPostFrameCallback((_) {
                         ^

**Comment by vasilich6107** [comment]
@hs029 check latest version
But you will not be happy with this update)))

Underlying package maintainer did breaking changes
https://pub.dev/packages/dropdown_search/changelog
