### ISSUE TITLE
reactive_flutter_rating_bar dependency issue

### ISSUE THREAD

**Issue by hs029** [artflutter/reactive_forms_widgets#52]
Dependency issue:

Running "flutter pub get" in ilearn...                          
Because reactive_flutter_rating_bar 0.2.0 depends on reactive_forms ^12.0.0 and no versions of reactive_flutter_rating_bar match >0.2.0 <0.3.0, reactive_flutter_rating_bar ^0.2.0 requires reactive_forms ^12.0.0.
So, because ilearn depends on both reactive_flutter_rating_bar ^0.2.0 and reactive_forms ^13.0.0, version solving failed.
pub get failed (1; So, because ilearn depends on both reactive_flutter_rating_bar ^0.2.0 and reactive_forms ^13.0.0, version solving failed.)

**Comment by vasilich6107** [comment]
Use dependency override while waiting for update

**Comment by vasilich6107** [comment]
reactive_flutter_rating_bar: ^0.3.0
