### ISSUE TITLE
What type of reactive field do you think is missing?

### ISSUE THREAD

**Issue by vasilich6107** [artflutter/reactive_forms_widgets#6]
This is an umbrella issue where I want to collect all requests for missing field types.

Leave here your favorite packegaes which do not have wrappers. Write several words about the reasons you need particular package. Note that packages without non-nullability support will be ignored.

If you want any custom control to be implemented - write a full description of functionality and attach the design.

There is no guarantee that your request will be fulfilled. At least we can collect and arrange community requirements for further contributors.

**Comment by Reprevise** [comment]
@vasilich6107 I commented on #1 if you want to take a look at a new field.

**Comment by kuhnroyal** [comment]
Been thinking about this for a while. I wonder if it is better to convert these widgets into smaller packages à la `reactive_forms_date_picker`, `reactive_forms_image_picker` - this way users can pick the individual widgets they need. I have witnessed the dependency hell with the form_builder package and I am not looking forward to it again. Otherwise this project is an umbrella for all kinds of dependencies that are not used but conflict with other dependencies.

Just an idea.
I know it more work managing the packages but it should be doable.

**Comment by vasilich6107** [comment]
@kuhnroyal it’s a valid point
I was thinking about splitting to multiple packages as far as not all deps support non-nullability and this blocs whole package

**Comment by vasilich6107** [comment]
@ joanpablo do you have an idea about separate packages naming pattern?

**Comment by joanpablo** [comment]
I totally agree with @kuhnroyal, I think each advanced widget should have its own package. And Reactive Forms Widget could be a repo that groups the others: a Mono Repo.

In my opinion the name pattern should by **reactive_<the_name_of_the_widget>**, the same you name the widgets:

* reactive_date_time_picker - ReactiveDateTimePicker
* reactive_date_range_picker - ReactiveDateRangePicker
* reactive_dropdown_search - ReactiveDropdownSearch
* reactive_touch_spin - ReactiveTouchSpin
* reactive_segmented_control - ReactiveSegmentedControl
* reactive_image_picker - ReactiveImagePicker

 If you ask me, I will also ask the creator of important widget plugins of the community to create a version of its plugins for reactive forms (I will look for some interesting plugins that have great popularity and that I consider they are very useful in real projects).

**Comment by kuhnroyal** [comment]
One widget I quiet often need is some form of multi-select.

**Comment by vasilich6107** [comment]
@kuhnroyal I started extraction packages into separate repos
first one is https://pub.dev/packages/reactive_date_time_picker

**Comment by kuhnroyal** [comment]
Good job, using this as of now.

**Comment by prakash-indorkar** [comment]
Reactive Implementation of Multi Image Picker
https://pub.dev/packages/multi_image_picker

**Comment by vasilich6107** [comment]
https://pub.dev/packages/sleek_circular_slider

**Comment by vasilich6107** [comment]
https://pub.dev/packages/multi_select_flutter

**Comment by sokolej79** [comment]
Autocomplete single select  (like type ahead)
Autocomplete multi select with chips
both with data from server not locally.

**Comment by vasilich6107** [comment]
@sokolej79 do you have any examples from pub.dev?

**Comment by sokolej79** [comment]
For autocmplete:
https://pub.dev/packages/flutter_typeahead
For autocomplete multiselect:
-could be combined widget with autocomplete and chips. User search and select with typeahead and when selected add value to chips, clears autocomplete text and can search new value again and repeat (multi values)

**Comment by sokolej79** [comment]
I have built some app with reactive_forms that:
- all data and settings for dynamic forms are on server,
-json settings have like formly structure: formOptions, fields and field groups (with template options, field type, settings, readonly, hidden, validators...) all in json and  can have tabs or single form.
-form page that creates all formControls with validators, initall values and pass down to form container widget and then builds form field widgets on the fly
-model for form is on server tables, paired with table name and json key name with client form
-validators on json are array string and client resolve based on balidator name on client
-supports for insert, update and readonly form
-controlled by main form page  for submitting form, cannot submit if invalid or pristine
-validation messages
-I have built custom fields: date, datetime, range picker, autocomplete, multiselect autocomplete, checkboxes groups, select and multi select without autocomplete, datetime now, inputs (text, numeric, textarea, attachments field with camera and thumbs)
-server is currently hasura, but we do lot of stuf with asp.net core or node
-It is working but a lot more has to be done. Cross field dependencies is a pain from json

**Comment by stact** [comment]
- Chips selection (single and multi)
- Slider
- Phone (region + validation https://github.com/google/libphonenumber/tree/master/java/libphonenumber )

**Comment by vasilich6107** [comment]
@stact you can find slider here https://github.com/joanpablo/reactive_forms/blob/master/lib/src/widgets/reactive_slider.dart

**Comment by naamapps** [comment]
@vasilich6107 Reactive CupertinoTextField would be an awesome addition

**Comment by vasilich6107** [comment]
@naamapps https://pub.dev/packages/reactive_cupertino_text_field

**Comment by naamapps** [comment]
@vasilich6107 wow that was quick, thank you!

**Comment by naamapps** [comment]
@vasilich6107 Also this package
https://pub.dev/packages/flutter_mentions
Would be great as a reactive widget

**Comment by leoshusar** [comment]
I have just published my Material month picker (the other existing one is unmaintained) and I'd be glad if it could be supported too
https://pub.dev/packages/mat_month_picker_dialog

**Comment by vasilich6107** [comment]
@leoshusar thanks for suggestion
Will try to add it

**Comment by vasilich6107** [comment]
@leoshusar 
What was the reason of creating your own package while there is existing https://pub.dev/packages/month_picker_dialog ?

**Comment by leoshusar** [comment]
Because it's unmaintained. It depends on old rxdart (you have to use override dependency) and has some bugs (issues are opened there without any notice).
I was using my implementation internally for some time, I thought maybe the author will return to it, but he doesn't seem to, so I've decided to release mine.

**Comment by vasilich6107** [comment]
Hi @leoshusar isn't it better to fork and continue maintaining?
For example that package supports `locale` and `rtl`...

**Comment by vasilich6107** [comment]
But it seems that is misses some properties...

**Comment by leoshusar** [comment]
Well for me it was easier and faster to write my own, I have chosen completely different approach on how it works. Even the author himself has opened an [issue](https://github.com/hmkrivoj/month_picker_dialog/issues/32) he would like to untangle the spaghetti code.
`rtl` works just as fine in mine.

But feel free to use whichever one you want :)

**Comment by vasilich6107** [comment]
@sokolej79 i finally did it
https://pub.dev/packages/reactive_flutter_typeahead
