### ISSUE TITLE
Update intl version

### ISSUE THREAD

**Issue by Reprevise** [artflutter/reactive_forms_widgets#7]
`reactive_forms` just updated their intl version which is causing a dependency conflict with this package. Please update the version of `intl`

**Comment by vasilich6107** [comment]
Technically there were no need to update intl in reactive forms. As far as 0.17.0 utilizes nonullability feature while reactive forms does not.

**Comment by Reprevise** [comment]
@vasilich6107 Can you update to the latest `reactive_forms` version?

**Comment by vasilich6107** [comment]
updated in 0.5.0

**Comment by vasilich6107** [comment]
I started extraction packages into separate repos
first one is https://pub.dev/packages/reactive_date_time_picker
