### ISSUE TITLE
Support for reactive_forms: ^9.1.0

### ISSUE THREAD

**Issue by alandotic** [artflutter/reactive_forms_widgets#8]
As stated, i couldn't install this library cause the targeted version is reactive_forms: ^8.0.3

**Comment by vasilich6107** [comment]
updated in 0.5.0

**Comment by alandotic** [comment]
@vasilich6107 

i am using intl ^0.17.0 and came across this deps issue

`Because every version of reactive_forms_widgets depends on flutter_touch_spin ^1.0.1 which depends on intl ^0.16.1, every version of reactive_forms_widgets requires intl ^0.16.1.`

**Comment by vasilich6107** [comment]
I’ll update reactive touch spin today

**Comment by vasilich6107** [comment]
I started extraction packages into separate repos
first one is https://pub.dev/packages/reactive_date_time_picker
