### ISSUE TITLE
ReactiveImagePicker - multiple image picker example

### ISSUE THREAD

**Issue by prakash-indorkar** [artflutter/reactive_forms_widgets#9]
Thanks for the amazing work guys. I had a quick question - when would this package have support for flutter 2.x?

And another question related to ReactiveImagePicker - can it pic multiple images.  

I am trying to figure out how to provide initial data for image/s ( could not find in the example), 
On the edit form can it load an image from URL, if the user replaces/select a new image, can it provide a new path or else ignore it.

I am trying to build something like 
![pic3](https://user-images.githubusercontent.com/60499738/110975242-7f9fcc00-8385-11eb-9a06-bec12a905eca.jpg)
![pic2](https://user-images.githubusercontent.com/60499738/110975262-86c6da00-8385-11eb-89c8-2028054239bf.jpg)
![pic1](https://user-images.githubusercontent.com/60499738/110975274-8a5a6100-8385-11eb-8c5c-500164020d3b.jpeg)

**Comment by vasilich6107** [comment]
Flutter v2 support will arrive after reactive forms null safety support

**Comment by vasilich6107** [comment]
Check this
https://pub.dev/packages/reactive_multi_image_picker

**Comment by prakash-indorkar** [comment]
@vasilich6107 .. thanks for the really quick building of this widget.  Just another request to provide the example, along with code for how to prefill initial values ( list of image URLs ) at the time of editing form.
really appreciated. :)

**Comment by vasilich6107** [comment]
You’ll have to handle that somehow manually by combining in grid the list of existing images and selected assets.

https://github.com/Sh1d0w/multi_image_picker/issues/436

**Comment by vasilich6107** [comment]
Use `imagePickerBuilder` to build your own grid

**Comment by vasilich6107** [comment]
I have some ideas.
I’ll update the package and example

**Comment by vasilich6107** [comment]
Updated package and example. Clone repo and launch example to see how to

**Comment by prakash-indorkar** [comment]
HI @vasilich6107 .. Thank you so much for your great solution and example. This is really helpful. 

However, I'm getting this error on pub get. (I did override temporarily to ^8.0.3 for getting this work)
Because reactive_forms_widgets 0.4.1 depends on reactive_forms ^8.0.3 and no versions of reactive_forms_widgets match >0.4.1 <0.5.0, reactive_forms_widgets ^0.4.1 requires reactive_forms ^8.0.3.

So, because myApp depends on both reactive_forms ^9.1.0 and reactive_forms_widgets ^0.4.1, version solving failed.


I think other widgets in this package needs to update with reactive_forms ^9.1.0

Another thing, the delete button on the middle deletes the image when clicked anywhere on the image, but I think I can fix it by moving the delete button on top-right corner of the image, with a positioned widget.

Rest all good. Excellent support.
Thanks, Prakash

**Comment by vasilich6107** [comment]
Do not use `reactive_forms_widgets`

**Comment by vasilich6107** [comment]
Every widget now is a separate package

**Comment by vasilich6107** [comment]
You need https://pub.dev/packages/reactive_multi_image_picker

**Comment by vasilich6107** [comment]
all links to separate packages are in root readme
https://github.com/artflutter/reactive_forms_widgets

**Comment by prakash-indorkar** [comment]
ok.. got it. I have updated all separate packages now.

Another thing was Validation on multi_image. 
I did add ... `validators: [Validators.required],` no error message displayed when submit button clicked. 
Also how to set min and max ( again inside validation?) 
Thanks

**Comment by vasilich6107** [comment]
Required validator works only if value is null.
For all other cases you’ll have to write custom validators as far as MutliImage value is complex
